config/routes.rb
Rails.application.routes.draw do
  root :to => 'urls#new'
  post   '/urls', :to => 'urls#create', :as => 'shorten'

  get    '/info/:short', :to => 'urls#info', :as => 'url_info'
  get    '/:short', :to => 'urls#show'
end

app/models/url.rb
class Url < ActiveRecord::Base
  self.primary_key = 'short_url'

  before_create :validate_short_url

  KEY_LENGTH=8
  PROFANITIES = ["foo", "bar"]

  def validate_short_url
    Url::short_url_valid?(short_url)
  end

  def self.generate_short_url
    range = [*'0'..'9',*'A'..'Z',*'a'..'z']
    url = Array.new(KEY_LENGTH){ range.sample }.join

    until Url::short_url_valid?(url)
      url = Array.new(KEY_LENGTH){ range.sample }.join
    end

    url
  end

  def self.short_url_profane?(url)
    PROFANITIES.each do |p|
      return true if url.include?(p)
    end
    false
  end

  def self.short_url_valid?(url)
    !Url::short_url_has_neighbors?(url) && !Url::short_url_profane?(url)
  end

  def self.short_url_has_neighbors?(url)
    Url.all.each do |u|
      return true if Levenshtein::distance(u.short_url, url) <= 1
    end

    false
  end

  def self.find_close_to(url)
    Url.all.each do |u|
      return u if Levenshtein::distance(u.short_url, url) <= 1
    end

    nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def show
    url = Url.find_close_to params[:short]

    if url
      url.last_seen = Time.now
      url.view_count += 1
      url.save!
      redirect_to url.long_url
    else
      flash[:notice] = "We don't recognize this link."
      redirect_to root_url
    end
  end

  def info
    url = Url.find_close_to params[:short]
    if url
      render :json => url.to_json
    else
      response.status = 404
      render :nothing => true
    end
  end

  def new
    @url = Url.new
  end

  def create
    if params[:url][:long_url] && params[:url][:long_url].start_with?("http")
      params[:url][:short_url] = Url.generate_short_url unless params[:url][:short_url]
      url = Url.create user_params

      long_url = "<a href='#{url.long_url.html_safe}'>#{url.long_url.html_safe}</a>"
      short_url = "<a href='#{url.short_url.html_safe}'>#{request.protocol}#{request.domain}/#{url.short_url.html_safe}</a>"
      flash.now[:notice] = "Shortened #{long_url} to #{short_url}. Enjoy!"
    else
      if params[:url][:long_url].present?
        flash.now[:error] = "Babylinks will only shorten http or https urls."
      else
        flash.now[:error] = "Babylinks needs a url to generate a short url to point to."
      end
      response.status = 400
    end

    @url = Url.new
    render :new
  end

  private

  def user_params
    params.require(:url).permit(:long_url, :short_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
 def route
    "#{ params[:controller] }/#{ params[:action] }"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Babylinks</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body data-route='<%= route %>'>

<%= yield %>

</body>
</html>

app/views/urls/new.html.erb
<h1 class="h1">
  Babylinks - Yet Another Url Shortener
</h1>

<% if flash[:error] %>
  <div class="flash error">
    <%= raw flash[:error] %>
  </div>
<% end %>

<% if flash[:notice] %>
  <div class="flash notice">
    <%= raw flash[:notice] %>
  </div>
<% end %>

<%= form_for @url, :url => shorten_path do |u| %>
  <div>
    <%= u.label "Shorten This" %>:
    <%= u.text_field :long_url %>
  </div>
  <div>
    <%= u.submit "Create"%>
  </div>
<% end %>